---
sudo: required
services:
  - docker
env:
  - playbook: test-as-root.yml

before_install:
  # Install Ansible.
  - pip install ansible

install:
  - cd tests
  - ansible-playbook install-dependencies.yml

script:
  - ansible-playbook -i inventory_travis run-container.yml
