##
# drush tasks
#
---
- name: Installing dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - git
    - mysql-client
  become: yes
  become_user: root

- name: Install drush
  shell: >
    COMPOSER_HOME={{ composer_home_path|default('~/.composer') }} \
    composer global require drush/drush:{{ drush_version }}
    creates={{ drush_script_path }}
  environment:
    TERM: xterm

- name: Register system-wide drush launcher
  shell: |
    SCRIPT=$(readlink -f {{ drush_script_path }})
    echo "#!/bin/bash
    $SCRIPT \$@" > {{ drush_system_launcher_path }}
    chmod +x {{ drush_system_launcher_path }}
    creates={{ drush_system_launcher_path }}
  when: drush_add_system_launcher|bool
  become: yes
  become_user: root
