##
# drush tasks
#
---
- name: Installing dependencies
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=86400
  with_items:
    - git
    - mysql-client
  sudo: yes
  sudo_user: root

- name: Install drush
  shell: >
    composer global require drush/drush:{{ drush_version }}
  environment:
    TERM: xterm

- name: Add a drush wrapper script
  shell: |
    echo '#!/bin/bash
    {{ drush_script_path }} $@' > /usr/local/bin/drush
    chmod +x /usr/local/bin/drush
    creates=/usr/local/bin/drush