##
# drush tasks
#
---
- name: Installing dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - git
    - mysql-client
  sudo: yes
  sudo_user: root

- name: Install drush
  shell: >
    composer global require drush/drush:{{ drush_version }}
    creates={{ drush_script_path }}
  environment:
    TERM: xterm

- name: Register system-wide drush launcher
  shell: |
    echo '#!/bin/bash
    {{ drush_script_path }} $@' > {{ drush_system_launcher_path }}
    chmod +x {{ drush_system_launcher_path }}
    creates={{ drush_system_launcher_path }}
  when: drush_add_system_launcher|bool
  sudo: yes
  sudo_user: root