##
# drush tasks
#
---
- name: Install dependencies.
  apt: pkg={{ item }} state=present
  with_items:
    - git
    - mysql-client
  become: yes
  become_user: root
  when: not drush_skip_root_setup

- name: Determine global composer home
  shell: "echo $HOME/.composer"
  changed_when: false
  register: result

- name: Install drush
  composer:
    command: "require"
    arguments: "drush/drush={{ drush_version }} --update-with-dependencies"
    working_dir: "{{ composer_home_path|default(composer_home_path_default) }}"
  vars:
    composer_home_path_default: '{{ result.stdout }}'
  environment:
    COMPOSER_DISCARD_CHANGES: 1

- name: Register system-wide drush launcher.
  shell: |
    SCRIPT=$(readlink -f {{ drush_script_path }})
    echo "#!/bin/bash
    $SCRIPT \$@" > {{ drush_system_launcher_path }}
    chmod +x {{ drush_system_launcher_path }}
    creates={{ drush_system_launcher_path }}
  when: drush_add_system_launcher|bool and not drush_skip_root_setup
  become: yes
  become_user: root
